"""
OpenAI RFT (Reinforcement Fine-Tuning) configuration for uk_arable_manager.

IMPORTANT — ASSUMPTION ISOLATION
=================================
As of April 2026, OpenAI's managed RFT API for o4-mini requires:
  1. A JSONL training file uploaded via the Files API.
  2. A grader definition (Python script or structured spec) attached to the job.
  3. A fine-tuning job created via POST /v1/fine_tuning/jobs with method="reinforcement".

The exact API shapes below are based on OpenAI documentation available at
fine-tuning job creation time.  If the API changes, this is the ONLY file
that needs updating.

References:
  https://platform.openai.com/docs/guides/reinforcement-fine-tuning
  OpenAI Python SDK: openai >= 1.30.0
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

# ── Target model ──────────────────────────────────────────────────────────────
RFT_MODEL = "o4-mini-2025-04-16"

# ── Assumed RFT hyperparameters (isolated here for easy override) ─────────────
DEFAULT_HYPERPARAMETERS: Dict[str, Any] = {
    "n_epochs": 1,              # RFT typically uses 1 epoch over rollout data
    "batch_size": "auto",
    "learning_rate_multiplier": "auto",
    "reasoning_effort": "medium",  # o4-mini reasoning effort for rollouts
}

# ── Grader script template ────────────────────────────────────────────────────
# ASSUMPTION: OpenAI RFT expects a Python grader that:
#   - Is uploaded as a file
#   - Exports a `grade(sample) -> float` function where sample has
#     .input (list of messages), .output (model response string), .metadata (dict)
#   - Returns a float in [0, 1]
#
# The grader receives metadata we embed in each training example.

GRADER_SCRIPT_TEMPLATE = '''"""
OpenAI RFT grader for uk_arable_manager.
Auto-generated by openai_rft_config.py — do not edit by hand.

OpenAI RFT calls grade(sample, item) -> float in [0, 1]
  sample: the model's rollout output (dict with "choices"/"output_text"/etc.)
  item:   one line of the training JSONL (dict with "messages" and "metadata")

For uk_arable_manager, the terminal_score is known at dataset-build time
(from the simulator ground truth) and embedded in item["metadata"].
This grader simply returns the normalised terminal_score.
"""
import re
import json


def _extract_text(sample) -> str:
    if isinstance(sample, dict):
        if "output_text" in sample:
            return str(sample["output_text"])
        if "choices" in sample and sample["choices"]:
            msg = sample["choices"][0].get("message") or {}
            return str(msg.get("content") or "")
        if "content" in sample:
            return str(sample["content"])
    return str(sample) if sample is not None else ""


def grade(sample, item) -> float:
    """
    Return the scalar_final_score for this episode in [0, 1].
    Pulls the simulator ground-truth terminal_score from item.metadata.
    """
    metadata = {}
    if isinstance(item, dict):
        metadata = item.get("metadata") or {}

    ts = metadata.get("terminal_score")
    if ts is not None:
        try:
            return float(max(0.0, min(1.0, float(ts))))
        except (TypeError, ValueError):
            pass

    # Fallback: parse terminal_score from the model output text
    text = _extract_text(sample)
    m = re.search(r"terminal[_ ]score[:\\s]+([0-9.]+)", text, re.IGNORECASE)
    if m:
        try:
            return float(max(0.0, min(1.0, float(m.group(1)))))
        except ValueError:
            pass
    return 0.0
'''

# ── RFT job manifest dataclass ────────────────────────────────────────────────

@dataclass
class RFTJobManifest:
    """
    Full specification for an OpenAI RFT fine-tuning job.
    Serialise with .to_api_payload() to pass to the OpenAI SDK.

    ASSUMPTION: OpenAI fine_tuning.jobs.create() with method="reinforcement"
    accepts this payload shape.  Verify against current SDK docs before launch.
    """
    model: str = RFT_MODEL
    training_file_id: str = ""           # populated after file upload
    validation_file_id: Optional[str] = None
    grader_file_id: Optional[str] = None # uploaded grader script
    suffix: str = "uk-arable"
    hyperparameters: Dict[str, Any] = field(default_factory=lambda: dict(DEFAULT_HYPERPARAMETERS))
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_api_payload(self) -> Dict[str, Any]:
        """
        Build the payload dict for openai.fine_tuning.jobs.create().
        ASSUMPTION: method="reinforcement" is the correct parameter for RFT.
        """
        payload: Dict[str, Any] = {
            "model": self.model,
            "training_file": self.training_file_id,
            "method": "reinforcement",            # ASSUMPTION
            "suffix": self.suffix,
            "hyperparameters": self.hyperparameters,
        }
        if self.validation_file_id:
            payload["validation_file"] = self.validation_file_id
        if self.grader_file_id:
            payload["grader"] = {"file_id": self.grader_file_id}  # ASSUMPTION
        if self.metadata:
            payload["metadata"] = self.metadata
        return payload


# ── Training example format ───────────────────────────────────────────────────

@dataclass
class RFTTrainingExample:
    """
    One training example in the expected JSONL format.

    ASSUMPTION: OpenAI RFT training JSONL uses the same messages format as
    supervised fine-tuning, with an additional "metadata" key that is passed
    to the grader at scoring time.

    Format per line:
    {
      "messages": [
        {"role": "system",    "content": "..."},
        {"role": "user",      "content": "..."},
        {"role": "assistant", "content": "..."}  // model's rollout transcript
      ],
      "metadata": {
        "terminal_score": 0.72,
        "task_id": "...",
        ...
      }
    }
    """
    messages: List[Dict[str, str]]
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {"messages": self.messages, "metadata": self.metadata}


# ── Eval result format ────────────────────────────────────────────────────────

@dataclass
class RFTEvalResult:
    task_id: str
    split: str
    model_version: str
    terminal_score: float
    ending_cash: float
    mean_final_soil: float
    ever_bankrupt: bool
    quarters_completed: int
    grader_variant: str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "task_id": self.task_id,
            "split": self.split,
            "model_version": self.model_version,
            "terminal_score": self.terminal_score,
            "ending_cash": self.ending_cash,
            "mean_final_soil": self.mean_final_soil,
            "ever_bankrupt": self.ever_bankrupt,
            "quarters_completed": self.quarters_completed,
            "grader_variant": self.grader_variant,
        }
