"""
OpenAI RFT (Reinforcement Fine-Tuning) configuration for uk_arable_manager.

IMPORTANT — ASSUMPTION ISOLATION
=================================
As of April 2026, OpenAI's managed RFT API for o4-mini requires:
  1. A JSONL training file uploaded via the Files API.
  2. A grader definition (Python script or structured spec) attached to the job.
  3. A fine-tuning job created via POST /v1/fine_tuning/jobs with method="reinforcement".

The exact API shapes below are based on OpenAI documentation available at
fine-tuning job creation time.  If the API changes, this is the ONLY file
that needs updating.

References:
  https://platform.openai.com/docs/guides/reinforcement-fine-tuning
  OpenAI Python SDK: openai >= 1.30.0
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

# ── Target model ──────────────────────────────────────────────────────────────
RFT_MODEL = "o4-mini-2025-04-16"

# ── Assumed RFT hyperparameters (isolated here for easy override) ─────────────
DEFAULT_HYPERPARAMETERS: Dict[str, Any] = {
    "n_epochs": 1,              # RFT typically uses 1 epoch over rollout data
    "batch_size": "auto",
    "learning_rate_multiplier": "auto",
    "reasoning_effort": "medium",  # o4-mini reasoning effort for rollouts
}

# ── Grader script template ────────────────────────────────────────────────────
# ASSUMPTION: OpenAI RFT expects a Python grader that:
#   - Is uploaded as a file
#   - Exports a `grade(sample) -> float` function where sample has
#     .input (list of messages), .output (model response string), .metadata (dict)
#   - Returns a float in [0, 1]
#
# The grader receives metadata we embed in each training example.

GRADER_SCRIPT_TEMPLATE = '''"""
OpenAI RFT grader for uk_arable_manager.
Auto-generated by openai_rft_config.py — do not edit by hand.

ASSUMPTION: OpenAI RFT calls grade(sample) where sample has:
  sample.output  — model's final answer / response string
  sample.metadata — dict we attached during dataset creation, containing:
    "terminal_score"   : float  (from simulator, our ground truth)
    "starting_cash"    : float
    "ending_cash"      : float  (if available from rollout)
    "mean_final_soil"  : float
    "ever_bankrupt"    : bool
    "grader_variant"   : str    ("scalar_final_score" | "bankruptcy_aware" | "stewardship_weighted")
"""
import re
import json


def grade(sample) -> float:
    """
    Primary grader: return the scalar_final_score from the episode metadata.

    For RFT the model's output is the sequence of tool calls across 40 quarters.
    The score comes from the episode outcome, not from parsing the text.
    """
    metadata = getattr(sample, "metadata", {}) or {}
    if not metadata:
        try:
            metadata = json.loads(getattr(sample, "metadata_json", "{}"))
        except Exception:
            pass

    terminal_score = metadata.get("terminal_score")
    if terminal_score is not None:
        # Clamp to [0, 1]
        return float(max(0.0, min(1.0, terminal_score)))

    # Fallback: try to extract a numeric score from the output text
    output = getattr(sample, "output", "") or ""
    match = re.search(r"terminal_score[:\\s]+([0-9.]+)", output, re.IGNORECASE)
    if match:
        return float(max(0.0, min(1.0, float(match.group(1)))))

    return 0.0
'''

# ── RFT job manifest dataclass ────────────────────────────────────────────────

@dataclass
class RFTJobManifest:
    """
    Full specification for an OpenAI RFT fine-tuning job.
    Serialise with .to_api_payload() to pass to the OpenAI SDK.

    ASSUMPTION: OpenAI fine_tuning.jobs.create() with method="reinforcement"
    accepts this payload shape.  Verify against current SDK docs before launch.
    """
    model: str = RFT_MODEL
    training_file_id: str = ""           # populated after file upload
    validation_file_id: Optional[str] = None
    grader_file_id: Optional[str] = None # uploaded grader script
    suffix: str = "uk-arable"
    hyperparameters: Dict[str, Any] = field(default_factory=lambda: dict(DEFAULT_HYPERPARAMETERS))
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_api_payload(self) -> Dict[str, Any]:
        """
        Build the payload dict for openai.fine_tuning.jobs.create().
        ASSUMPTION: method="reinforcement" is the correct parameter for RFT.
        """
        payload: Dict[str, Any] = {
            "model": self.model,
            "training_file": self.training_file_id,
            "method": "reinforcement",            # ASSUMPTION
            "suffix": self.suffix,
            "hyperparameters": self.hyperparameters,
        }
        if self.validation_file_id:
            payload["validation_file"] = self.validation_file_id
        if self.grader_file_id:
            payload["grader"] = {"file_id": self.grader_file_id}  # ASSUMPTION
        if self.metadata:
            payload["metadata"] = self.metadata
        return payload


# ── Training example format ───────────────────────────────────────────────────

@dataclass
class RFTTrainingExample:
    """
    One training example in the expected JSONL format.

    ASSUMPTION: OpenAI RFT training JSONL uses the same messages format as
    supervised fine-tuning, with an additional "metadata" key that is passed
    to the grader at scoring time.

    Format per line:
    {
      "messages": [
        {"role": "system",    "content": "..."},
        {"role": "user",      "content": "..."},
        {"role": "assistant", "content": "..."}  // model's rollout transcript
      ],
      "metadata": {
        "terminal_score": 0.72,
        "task_id": "...",
        ...
      }
    }
    """
    messages: List[Dict[str, str]]
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {"messages": self.messages, "metadata": self.metadata}


# ── Eval result format ────────────────────────────────────────────────────────

@dataclass
class RFTEvalResult:
    task_id: str
    split: str
    model_version: str
    terminal_score: float
    ending_cash: float
    mean_final_soil: float
    ever_bankrupt: bool
    quarters_completed: int
    grader_variant: str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "task_id": self.task_id,
            "split": self.split,
            "model_version": self.model_version,
            "terminal_score": self.terminal_score,
            "ending_cash": self.ending_cash,
            "mean_final_soil": self.mean_final_soil,
            "ever_bankrupt": self.ever_bankrupt,
            "quarters_completed": self.quarters_completed,
            "grader_variant": self.grader_variant,
        }
