"""
OpenAI RFT grader for uk_arable_manager.
Auto-generated by openai_rft_config.py — do not edit by hand.

ASSUMPTION: OpenAI RFT calls grade(sample) where sample has:
  sample.output  — model's final answer / response string
  sample.metadata — dict we attached during dataset creation, containing:
    "terminal_score"   : float  (from simulator, our ground truth)
    "starting_cash"    : float
    "ending_cash"      : float  (if available from rollout)
    "mean_final_soil"  : float
    "ever_bankrupt"    : bool
    "grader_variant"   : str    ("scalar_final_score" | "bankruptcy_aware" | "stewardship_weighted")
"""
import re
import json


def grade(sample) -> float:
    """
    Primary grader: return the scalar_final_score from the episode metadata.

    For RFT the model's output is the sequence of tool calls across 40 quarters.
    The score comes from the episode outcome, not from parsing the text.
    """
    metadata = getattr(sample, "metadata", {}) or {}
    if not metadata:
        try:
            metadata = json.loads(getattr(sample, "metadata_json", "{}"))
        except Exception:
            pass

    terminal_score = metadata.get("terminal_score")
    if terminal_score is not None:
        # Clamp to [0, 1]
        return float(max(0.0, min(1.0, terminal_score)))

    # Fallback: try to extract a numeric score from the output text
    output = getattr(sample, "output", "") or ""
    match = re.search(r"terminal_score[:\s]+([0-9.]+)", output, re.IGNORECASE)
    if match:
        return float(max(0.0, min(1.0, float(match.group(1)))))

    return 0.0
